FROM {{ namespace }}/{{ image_prefix }}pacemaker-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block pacemaker_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_pacemaker_extend_start
COPY check_alive.sh /
COPY dummy_service.sh /
COPY anything /usr/lib/ocf/resource.d/heartbeat/
RUN chmod 755 /usr/local/bin/kolla_pacemaker_extend_start /check_alive.sh /dummy_service.sh /usr/lib/ocf/resource.d/heartbeat/anything

{% block pacemaker_footer %}{% endblock %}
{% block footer %}{% endblock %}
