FROM {{ namespace }}/{{ image_prefix }}pacemaker-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block pacemaker_header %}{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_pacemaker_extend_start
RUN chmod 755 /usr/local/bin/kolla_pacemaker_extend_start

{% block pacemaker_footer %}{% endblock %}
{% block footer %}{% endblock %}
