FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block neutron_server_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set neutron_server_packages = [
            'openstack-neutron-lbaas',
            'openstack-neutron-vpnaas',
        ] %}

    {% elif base_distro in ['ubuntu'] %}

        {% set neutron_server_packages = [
            'neutron-lbaasv2-agent',
            'python-neutron-lbaas',
            'python-neutron-vpnaas',
        ] %}

    {% endif %}
{% endif %}

{{ macros.install_packages(neutron_server_packages | customizable("packages")) }}

ADD plugins-archive /
COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start \
    && if [ "$(ls /plugins)" ]; then \
           pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /plugins/*; \
       fi

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
      {% set plugin_packages = ['python-networking-odl'] %}

      {% if plugin_packages_repo is not defined %}
        {% set plugin_packages_repo = 'networking-odl.repo' %}
      {% endif %}
COPY {{ plugin_packages_repo }} /etc/yum.repos.d/
{{ macros.install_packages(plugin_packages | customizable("packages")) }}
    {% endif %}
{% endif %}

{% block neutron_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
