FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block opendaylight_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='odl') }}

{% block opendaylight_install %}
RUN yum install -y https://nexus.opendaylight.org/content/repositories/opendaylight-nitrogen-epel-7-x86_64-devel/org/opendaylight/integration-packaging/opendaylight/7.2.0-0.1.20180116snap254.el7.noarch/opendaylight-7.2.0-0.1.20180116snap254.el7.noarch.rpm
{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block opendaylight_footer %}{% endblock %}
{% block footer %}{% endblock %}
